# Generated by Django 5.0.4 on 2024-04-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_contact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='surname',
        ),
    ]
