# Generated by Django 5.0.4 on 2024-04-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_first_name_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='telefon',
        ),
    ]
