# Generated by Django 5.0.4 on 2024-04-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_contact_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bgcolor',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
