# Generated by Django 5.0.4 on 2024-04-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contact_bgcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='bgcolor',
            field=models.CharField(default='#0038FF', max_length=7),
        ),
    ]
