# Generated by Django 5.0.4 on 2024-05-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_task_created_at_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='bgcolor',
            field=models.CharField(blank=True, default='#0038FF', max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='bgcolor',
            field=models.JSONField(blank=True),
        ),
    ]
